### ISSUE TITLE
API endpoint "Factorylocations" in factoryinsight is not really functional

### ISSUE THREAD

**Issue by Sphingobium** [united-manufacturing-hub/united-manufacturing-hub#1210]
### Expected Behavior

Given how it is named, the factorylocations endpoint in factoryinsight should probably fetch the location and geohash of all the locations and append them into an interface

### Current Behavior

The function calls getDataRequests for the path parameters, then doesnt use them and then appends a fixed data row, then returns the data. 

### Steps to Reproduce

open http.go in factoryinsight and read line 1885 ff

### Context (Environment)

Found during API annotation scrolling through the code

### Possible Solution

Either the endpoint should be fixed to have an actual function or it should probably get removed

### Version

v0.9.x

### Anything else?

factoryinsight http.go line 1885 ff

func processFactoryLocationsRequest(c *gin.Context, getDataRequest getDataRequest) {

	var data datamodel.DataResponseAny
	data.ColumnNames = []string{"Location", "Metric", "Geohash"}

	fullRow := []interface{}{"Aachen", 80, "u1h2fe"}
	data.Datapoints = append(data.Datapoints, fullRow)

	c.JSON(http.StatusOK, data)
}

**Comment by DaruZero** [comment]
I would suggest to remove the function altogether, because a customer can already get a list of his locations with the enpoint `GET /:customer`.
If data like `Metric` and `Geohash` (apparently fetched by `processFactoryLocatoinsRequest`) could be useful, then I think it would be a great idea to merge `processFactoryLocatoinsRequest` with `GetLocations` in `factoryinsight/database.go`, so to have a single function that gets all the data about all the locations of a specific customer.

**Comment by DaruZero** [comment]
After further investigation I cuould't find any reference to `Metric` or `Geohash` in the database reference. I would then suggest to remove the funciton `processFactoryLocationsRequest`, if it's not reserved for future use
