### ISSUE TITLE
Database model Refactoring for Digital Shadow

### ISSUE THREAD

**Issue by Gornoka** [united-manufacturing-hub/united-manufacturing-hub#367]
Hello Everyone, thanks for the productive meeting this afternoon @Scarjit @JeremyTheocharis @larswitte ,
Below I will reference the branch with the different model design.

[umh Stack-V-dev-0.pdf](https://github.com/united-manufacturing-hub/united-manufacturing-hub/files/6871078/umh.Stack-V-dev-0.pdf)

![image](https://user-images.githubusercontent.com/45569834/126838010-6a73b226-0f41-4024-963a-4137b8ffba33.png)

**Comment by Gornoka** [comment]
The current branch where I have included the ddl etc can be found below.
https://github.com/Gornoka/united-manufacturing-hub/tree/367-DataModelChanges
please bear in mind that this is only WIP and that the DDL does not include the notes included in the images and PDF, especially the Timescale changes. Also the notes are not necessarily adapted to all components.

**Comment by Gornoka** [comment]
updated files from yesterday evening

**Comment by larswitte** [comment]
The `AssetID` will be used to identify single steps in the digital shadow use case. We should change the name to something more fitting e.g. `UnitID` or `StepID` to allow more flexible use. 
Doing it this way is beneficial, because we can describe one step/location with only one ID. We can still group multiple step ID's together and build bigger units.

**Comment by Scarjit** [comment]
@Gornoka The referenced branch: https://github.com/Gornoka/united-manufacturing-hub/tree/367-DataModelChanges is no longer valid, can you give me the DDL file elsewhere ?

**Comment by Gornoka** [comment]
Yes I will do so,
